#Appium and Devices
platformName = Android
deviceName = emulator-5554
automationName = UiAutomator2
appiumURL = http://127.0.0.1:4723/
app = src/test/resources/app/org-wikipedia.apk
appPackage = com.starwarsapp
appActivity = com.starwarsapp.MainActivity

#API
apiURL = https://swapi.info/api